Tela de login
aluisribeiro/petsaojoao-flutter pull request #17
Opened 2020-06-02 03:03 UTC by BellCristensen

Ainda está faltando o gradiente atrás do logo do pet são joão!

2020-06-04 13:42 UTC, aluisribeiro commented
Oi @BellCristensen , tudo bem? Você está tendo algum problema para fazer a correção do CodeFactor?

2020-06-07 01:30 UTC, vitoravelarmartins requested changes
Passar do CodeFactor,

2020-06-07 01:30 UTC, vitoravelarmartins commented on lib/screens/login/login.dart
> +    return null;
@BellCristensen  consegue retornar um false aqui ao invés de um null?

2020-06-08 23:19 UTC, vitoravelarmartins approved these changes

2020-06-08 23:20 UTC, vitoravelarmartins approved these changes

2020-06-08 23:20 UTC, merged