adicionando telas do chat
aluisribeiro/petsaojoao-flutter pull request #19
Opened 2020-06-06 12:14 UTC by brubsnog

2020-06-07 01:18 UTC, vitoravelarmartins requested changes
@brubsnog seguir padrões de pasta dentro de models temos uma pasta de utils do firebase.

2020-06-07 22:56 UTC, giovaniGdy commented on lib/screens/views/chatscreen.dart
> +);
A **_MAIN_** e o **_TEMA_** do projeto já estão definidos.

2020-06-07 22:57 UTC, giovaniGdy commented on lib/screens/views/chatscreen.dart
> +class MyApp extends StatelessWidget {
Renomear Classe de acordo com a funcionalidade.

2020-06-07 23:00 UTC, giovaniGdy commented on lib/utils/utils.dart
> +}
Deve seguir os padrões de organização do projeto, como o @vitoravelarmartins disse.
A parte lógica deve ser salva em um diretório dentro de **_lib/models_**, sugiro **back_chat_screen_**.

2020-06-08 19:53 UTC, giovaniGdy commented
@brubsnog você inverteu os nomes, para telas você deve criar um diretório **_chat_screens_**, dentro de **_lib/screens_**, enquanto a parte lógica (funções) deve ficar dentro de **_lib/models_**, em um diretório com o nome **_back_chat_screens_**

2020-06-08 23:25 UTC, giovaniGdy commented on lib/models/utils_chat/utils.dart
> +}
@brubsnog está parte também deve estar dentro de **_back_chat_screen_**.

2020-06-08 23:33 UTC, giovaniGdy commented on lib/screens/chat_screens/chatscreen.dart
> +);
O **_main_** e os **_temas_** já estão feitos no projeto.

2020-06-08 23:33 UTC, giovaniGdy commented on lib/screens/chat_screens/chatscreen.dart
> +class MyApp extends StatelessWidget {
Renomear a classe.

2020-06-08 23:34 UTC, giovaniGdy commented on lib/screens/chat_screens/chatscreen.dart
> +}
Passar a parte lógica para **_lib/models_**.

2020-06-08 23:36 UTC, giovaniGdy commented on lib/screens/chat_screens/chatscreen.dart
> +}
Essa parte não é necessária.

2020-06-08 23:41 UTC, giovaniGdy commented on lib/screens/chat_screens/chatscreen.dart
> +}
Poderia criar dois componentes, para essas classes: **_TextComposer_** e **_ChatMessage_**.
Você pode criar um diretório **_chat_screen_** dentro de lib/components e salvar neste repositório.

2020-06-08 23:43 UTC, giovaniGdy requested changes
@brubsnog preciso que faça algumas modificações.

2020-06-30 22:39 UTC, closed without merging