Cadastro de Tutor OK!
aluisribeiro/petsaojoao-flutter pull request #4
Opened 2020-04-23 12:46 UTC by vitoravelarmartins

Cadastro do Tutor OK! 🦧

2020-04-28 02:19 UTC, vitoravelarmartins commented
Por favor atualizar flutter do Actions para ultima versão.

2020-04-28 02:55 UTC, vitoravelarmartins commented
Foi feita atualização do arquivo "dart.yml" para que Actions rodasse uma versão mais atualizada do  Flutter, já que era necessario devidos algumas dependências do nosso projeto; Agora estamos rodando os teste em uma versão melhor e estável.

2020-04-29 23:26 UTC, vitoravelarmartins commented
No ultimo commit fizemos integração do firebase

2020-05-03 21:47 UTC, aluisribeiro requested changes
Oi @vitoravelarmartins, tudo bem? Anotei algumas coisas que acho que seriam interessantesalterar antes de finalizar a revisão. O que você acha?:

* Converter o código fonte para inglês, nada em português
* Extrair os textos de botões e labels para constantes, como por exemplo: const _labelOkButton = ‘ok’, os textos podem ser em português sem problemas
* Criar os diretórios componentes, screens e models e a adicionar tudo neles
* Remover os prints, usar estratégias como essa: https://pub.dev/packages/logger
* Por que não criar os formulários e validadores dessa forma?: https://www.youtube.com/watch?v=E9WBPMuC_10
* Não ficaria melhor extrair a lógica de validações para “models/validators”?
* Alterar o nome de todas as classes em camel case;

2020-05-04 01:16 UTC, vitoravelarmartins commented
Criar os diretórios componentes, screens e models e a adicionar tudo neles: **Não entendi**

2020-05-04 01:31 UTC, vitoravelarmartins commented
Por que não criar os formulários e validadores dessa forma?: https://www.youtube.com/watch?v=E9WBPMuC_10

Estamos usando uma dependência para criar mascaras de texto, a mesma não tem opção validador, por isso estou validando dessa forma, achei maior o peso visual da mascara do que do validador, mas se preferir fazemos assim, só que ficara RG, CPF, CEP, telefone e  whatsapp sem mascara.

2020-05-04 01:33 UTC, vitoravelarmartins commented
Alterar o nome de todas as classes em camel case:  **FEITO**👍🏾

2020-05-11 11:37 UTC, aluisribeiro commented
Oi Vitor, você poderia converter todos os commits do PR para um único commit?

2020-05-12 19:06 UTC, closed without merging