Screen Registro
aluisribeiro/petsaojoao-flutter pull request #7
Opened 2020-05-18 20:36 UTC by RenanBaldo

Envio das páginas de registro.

2020-05-20 00:16 UTC, giovaniGdy commented on lib/models/validators/reg_email_validator.dart
> +}
Já existe um validador de e-mail, é melhor fazer a reutilização do código.
O validador de e-mail esta em: _**/models/validators/email_validator.dart**_

2020-05-20 00:43 UTC, giovaniGdy commented on lib/screens/animal_reg_found/reg_info.dart
> +class Reg_Info extends StatelessWidget {
Mudar o nome da classe para CamelCase

2020-05-20 00:46 UTC, giovaniGdy requested changes
@RenanBaldo fizemos o review do código e precisamos que faça algumas modificações.
Fizemos comentários dentro do código.

2020-05-20 00:54 UTC, vitoravelarmartins commented on lib/screens/animal_reg_found/reg_info.dart
> +}
@RenanBaldo  criar uma classe separada para adicionar esses itens pode ser no mesmo arquivo mas criar uma classe separada

2020-05-20 01:46 UTC, vitoravelarmartins commented on lib/screens/animal_reg_found/reg_info.dart
> +class Reg_Info extends StatelessWidget {
@RenanBaldo  não sei se essa tela seria mais adequada para esse tipo de pegunta. No caso esta é uma splashScrem que não deveria ter funções de click. Acho melhor fazer uma tela pedindo os dados do animal primeiro e checkbox ou um ShowDialog() perguntado se ele gostaria de informar os dados para contato.
![melhorar visuuall](https://user-images.githubusercontent.com/43485388/82395698-6f97b400-9a22-11ea-8a1a-ea8655e1f081.PNG)

2020-05-20 01:47 UTC, vitoravelarmartins commented on lib/screens/animal_reg_found/contact_info.dart
> +
Nome das variáveis deve ser em inglês.

2020-05-22 17:28 UTC, aluisribeiro commented on lib/screens/animal_reg_found/reg_info.dart
> +class Reg_Info extends StatelessWidget {
Oi @vitoravelarmartins, acredito que o Renan fez dessa forma pois está assim no protótipo. Acho que se tivermos que mudar podemos discutir isso no protótipo primeiro. O que acha? Eu deixaria entrar assim agora e corrigimos depois.

2020-05-24 19:38 UTC, vitoravelarmartins commented on lib/screens/animal_reg_found/reg_info.dart
> +class Reg_Info extends StatelessWidget {
OK

2020-05-26 22:26 UTC, vitoravelarmartins commented on lib/screens/animal_reg_found/animal_reg_found.dart
> +                        builder: (context) => CamelCase()),
**"CamelCase"**    é a denominação em inglês para a prática de escrever as palavras compostas ou frases, onde cada palavra é iniciada com maiúsculas e unidas sem espaços. O certo aqui seria escrever nome da classe **RegInfo**

2020-05-26 22:28 UTC, vitoravelarmartins commented on lib/screens/animal_reg_found/animal_reg_found.dart
> +                        builder: (context) => CamelCase()),
![1200px-CamelCase svg](https://user-images.githubusercontent.com/43485388/82956362-031f3680-9f87-11ea-8a36-a47fcb91c9d6.png)

2020-06-02 23:11 UTC, closed without merging