Push notification
aluisribeiro/petsaojoao-flutter pull request #8
Opened 2020-05-18 23:41 UTC by ViniciusContini

Adicionando a features de push notification ao projeto.

2020-05-20 00:16 UTC, vitoravelarmartins commented on lib/main.dart
> +import 'package:petsaojoao/screens/notification/notification.dart';
Esse "import" não esta sendo usado pela classe MyApp

2020-05-20 00:36 UTC, vitoravelarmartins commented on lib/screens/notification/notification.dart
> +  String novoToken = "";
Nomes da variáveis devem ser em inglês.

2020-05-20 00:47 UTC, vitoravelarmartins commented on pubspec.yaml
> +
@ViniciusContini  por favor verificar erro que esta mostrando ao subir código. Acreditamos que e devido espaço deixado, para te ajudar nesses casos existe uma Extension do Visual Studio Code chamado ESLint, que ao salvar o código concatena e retira espaços desnecessários .

2020-05-20 00:51 UTC, vitoravelarmartins requested changes
@ViniciusContini  Por favor fazer alterações solicitadas nos comentários.

2020-05-21 21:59 UTC, ViniciusContini commented
Feito as alterações solicitadas.

2020-05-21 23:53 UTC, vitoravelarmartins approved these changes

2020-05-21 23:54 UTC, merged